"""Write docs/reports/data_quality_layout.md from the Phase 2b summary files and the database."""

# Annotations on Python 3.11.
from __future__ import annotations

# Paths and helpers.
from spacedesigner.data.common import cleaning_dir, read_json, repo_root

# Database counts, which need Postgres to be up.
from spacedesigner.data.db_load import db_counts


def table(headers: list[str], rows: list[list]) -> list[str]:
    """Return a Markdown table as a list of lines."""
    # Header row.
    lines = ["| " + " | ".join(headers) + " |"]
    # Separator row.
    lines.append("| " + " | ".join("---" for _ in headers) + " |")
    # Body rows.
    for row in rows:
        # One line per row.
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    # Blank line after the table.
    lines.append("")
    # Give the lines back.
    return lines


def build() -> str:
    """Assemble the full Markdown report."""
    # Summary files written by the Phase 2b scripts.
    priors = read_json(cleaning_dir() / "layout_priors.json")
    # Objaverse summary.
    objaverse = read_json(cleaning_dir() / "objaverse_summary.json")
    # Catalog summary.
    catalog = read_json(cleaning_dir() / "furniture_catalog_summary.json")
    # RAG summary.
    rag = read_json(cleaning_dir() / "rag_summary.json")
    # Synthetic manifest.
    synthetic = read_json(cleaning_dir() / "synthetic_manifest.json")
    # SUN section of the priors.
    sun = priors["sun_rgbd"]
    # Lines of the report.
    out: list[str] = [
        "# Phase 2b data quality report (layout, catalog, 3D, knowledge, synthetic)",
        "",
        "Generated by `uv run python scripts/layout_report.py` from "
        "`datasets/metadata/cleaning/*.json`.",
        "Every number below is measured from files on disk. Nothing comes from 3D-FRONT.",
        "",
        "## Layout priors",
        "",
        "Every published prior carries its sample count `n` and the minimum "
        "`min_n` it had to reach.",
        "Priors below the minimum are omitted and listed under 'Omitted priors'.",
        "",
        "### SUN RGB-D 3D boxes (`SUNRGBD.zip`, `annotation3Dfinal` and `annotation3Dlayout`)",
        "",
        f"- Images considered (Phase 2a cleaned set): {sun['images_considered']}.",
        f"- Objects kept after filtering: {sun['objects_kept']}.",
        f"- Rooms dropped, by reason: {sun['room_drops']}.",
        f"- Objects dropped, by reason: {sun['object_drops']}.",
        f"- 3D-annotated rooms kept per room type: {sun['rooms_kept_by_type']}.",
        "- Filters: unmapped class, not a 4-corner box, edge outside 0.05 to 4 "
        "m, centre outside the",
        "  layout floor polygon, 3D IoU above 0.5 with a larger box, fewer than 3 or more than 40",
        "  objects in the room. `null_entry` counts empty placeholders in the annotation files.",
        "- `no_mapped_room_type` rooms still feed the size and wall priors, but not the"
        "  per-room-type co-occurrence priors.",
        "- Wall distance is centre-to-nearest-layout-edge. The SUN layout polygon covers only the",
        "  visible walls, so distances are biased toward the visible side.",
        "",
        "Measured object sizes (metres, median of n boxes) and centre-to-wall distance:",
        "",
    ]
    # Size table.
    out += table(
        ["class", "n", "length p50", "width p50", "height p50", "wall dist p50 (n)"],
        [
            [
                c,
                v["n"],
                v["length_m"]["p50"],
                v["width_m"]["p50"],
                v["height_m"]["p50"],
                (
                    f"{sun['wall_distance'][c]['centre_to_wall_m']['p50']} "
                    f"({sun['wall_distance'][c]['n']})"
                )
                if c in sun["wall_distance"]
                else "omitted",
            ]
            for c, v in sun["object_size"].items()
        ],
    )
    # Co-occurrence section.
    out += ["Co-occurrence per room type (share of rooms with the class):", ""]
    # One row per class per room type would be long; show each room type's top classes.
    out += table(
        ["room type", "rooms", "top classes (share of rooms)"],
        [
            [
                rt,
                v["n_rooms"],
                ", ".join(
                    f"{c} {x['p_present']:.2f}"
                    for c, x in sorted(v["classes"].items(), key=lambda kv: -kv[1]["p_present"])[:6]
                ),
            ]
            for rt, v in sun["cooccurrence"].items()
        ],
    )
    # Structured3D section.
    s3d = priors["structured3d"]
    # Header.
    out += [
        "### Structured3D room sizes (`rooms.jsonl`)",
        "",
        f"- Rooms considered: {s3d['rooms_considered']}. Dropped as unmapped: {s3d['drops']}.",
        "- `hull_area_m2` is a convex-hull area, an upper bound for L-shaped rooms.",
        "- `bbox_3d.json` in the bbox zip has no class labels, so Structured3D "
        "gives room sizes only.",
        "  Per-class furniture sizes come from SUN RGB-D.",
        "",
    ]
    # Size table.
    out += table(
        [
            "room type",
            "n",
            "area p50 (m2)",
            "long edge p50 (m)",
            "short edge p50 (m)",
            "height p50",
        ],
        [
            [
                rt,
                v["n"],
                v["area_m2"]["p50"],
                v["long_edge_m"]["p50"],
                v["short_edge_m"]["p50"],
                v["height_m"]["p50"],
            ]
            for rt, v in s3d["room_size"].items()
        ],
    )
    # CubiCasa section.
    cc = priors["cubicasa5k"]
    # Header.
    out += [
        "### CubiCasa5K room shapes (dimensionless)",
        "",
        "CubiCasa5K polygons are in SVG units with no metre scale, so only aspect ratio and the",
        "share of the plan canvas are published. No object footprints exist there, so there are no",
        "wall distances from CubiCasa.",
        "",
    ]
    # Shape table.
    out += table(
        ["room type", "n", "aspect p50", "plan-area share p50"],
        [
            [rt, v["n"], v["aspect"]["p50"], v["plan_area_share"]["p50"]]
            for rt, v in cc["room_shape"].items()
        ],
    )
    # Omitted section.
    out += ["### Omitted priors (below the minimum sample count, or no source file)", ""]
    # Every omission across the sources.
    omitted = sun["omitted"] + s3d["omitted"] + cc["omitted"]
    # Table.
    out += table(
        ["prior", "n", "min n", "missing"],
        [[o["prior"], o["n"], o["min_n"], o["missing"]] for o in omitted],
    )
    # Objaverse section.
    out += [
        "## Objaverse cleanup (the 160 acquired GLBs only)",
        "",
        f"- Assets in the license log: {objaverse['assets_in_license_log']}. "
        f"Cleaned: {objaverse['assets_cleaned']}.",
        f"- Dropped, by reason: {objaverse['assets_dropped']}. The unmapped LVIS categories are",
        "  crib, drawer, headboard, and mattress; the taxonomy has no class for them.",
        f"- Classes: {objaverse['taxonomy_class_histogram']}.",
        f"- Up axis chosen: {objaverse['up_axis_source_histogram']}.",
        f"- Licenses kept per asset: {objaverse['license_histogram']}.",
        f"- Size on disk: {objaverse['source_bytes']} bytes before, "
        f"{objaverse['cleaned_bytes']} after. Large files (5 MB or more): "
        f"{objaverse['large_files']}.",
        f"- Scale rule: {objaverse['scale_rule']}",
        f"- Up-axis rule: {objaverse['up_axis_rule']}",
        "- Cleaned meshes are under `datasets/processed/objaverse/` (gitignored).",
        "",
        "## Furniture catalog",
        "",
        f"- Items: {catalog['items']} ({catalog['items_from_objaverse_meshes']} from cleaned "
        f"Objaverse mesh proportions, {catalog['items_from_sun_tiers']} from "
        f"SUN RGB-D size tiers).",
        f"- Items per category: {catalog['items_by_category']}.",
        f"- Categories with no items: {catalog['categories_without_items']}, because SUN RGB-D has "
        "too few 3D boxes for them.",
        f"- Mesh candidates dropped: {catalog['mesh_candidates_dropped']}.",
        "- Dimensions: SUN RGB-D measured percentile bands (small, medium, large tiers), or mesh",
        "  proportions scaled into the SUN interquartile length band. The "
        "source of every item is in",
        "  `datasets/metadata/cleaning/furniture_catalog_provenance.json`.",
        "- `style_tags` and `material` are project labels. They are not 3D-FUTURE labels.",
        f"- Prices are synthetic INR, not scraped: min {catalog['price_inr']['min']}, median "
        f"{catalog['price_inr']['median']}, max {catalog['price_inr']['max']}. Each price is a",
        "  per-class base times a size factor, a material factor, and noise. They only need to be",
        "  plausible for the optimizer.",
        "- `embedding` is null on every item.",
        "",
        "## RAG corpus",
        "",
        f"- Chunks: {rag['chunks_total']} by source {rag['chunks_by_source']}.",
        f"- ADA: {rag['ada_2010']['pdf_pages']} pages, "
        f"{rag['ada_2010']['header_footer_lines_removed']} header or footer lines removed.",
        f"- MoHUA: {rag['mohua_2021']['pdf_pages']} pages, "
        f"{rag['mohua_2021']['header_footer_lines_removed']} header or footer lines removed.",
        f"- Sections dropped as too short: ADA {rag['ada_2010']['sections_dropped']}, "
        f"MoHUA {rag['mohua_2021']['sections_dropped']}.",
        f"- Topics: {rag['chunks_by_topic']}.",
        "- The MoHUA text is all rights reserved and stored for retrieval only. Chunk text is in",
        "  `datasets/processed/rag/chunks.jsonl` and the database, never in a tracked file.",
        "- `embedding` is null on every chunk. Embeddings are Phase 6.",
        "",
        "## Synthetic generator v1",
        "",
        f"- Records: {synthetic['records']} scenes and {synthetic['records']} gold requirements,",
        "  all validated against the locked `SceneGraph` and `Requirement` schemas.",
        f"- Room types: {synthetic['room_type_counts']}.",
        f"- Rooms with must-keep objects: {synthetic['scenes_with_must_keep']}. "
        f"Accessibility required: {synthetic['accessibility_required']}. "
        f"Objects: {synthetic['objects_total']}.",
        "- Room sizes follow the Structured3D priors. Objects follow the SUN "
        "presence rates and sizes.",
        "- The full set is in `datasets/raw/synthetic/` (gitignored). The manifest and three",
        "  examples are in `datasets/metadata/cleaning/synthetic_manifest.json`.",
        "",
        "## Database",
        "",
    ]
    # Live counts from Postgres, if it is up.
    try:
        # Query the two tables.
        counts = db_counts()
        # Table of counts.
        out += table(
            ["table", "rows", "rows with null embedding"],
            [
                [
                    "furniture_catalog",
                    counts["furniture_catalog_rows"],
                    counts["furniture_catalog_null_embeddings"],
                ],
                ["rag_chunks", counts["rag_chunks_rows"], counts["rag_chunks_null_embeddings"]],
            ],
        )
    except Exception as error:  # noqa: BLE001 - the report must still build without Postgres
        # Say so instead of failing.
        out += [f"Database not reachable when this report was built ({type(error).__name__}).", ""]
    # The 3D-FRONT / 3D-FUTURE section.
    out += [
        "## What 3D-FRONT and 3D-FUTURE would have provided, and did not",
        "",
        "3D-FRONT and 3D-FUTURE are deferred. Their archives are not on disk, and nothing was",
        "downloaded or requested for this phase. These steps cannot run until they are added:",
        "",
        "- ATISS-style house flattening: turning 3D-FRONT houses into rooms with normalized room",
        "  types, object footprints from bounding boxes and scale factors, and "
        "the full filter set.",
        "  Here the same kinds of filters run on SUN RGB-D boxes only, which are single camera",
        "  views, not whole rooms.",
        "- Furnished-room statistics from complete layouts: object sizes per category, category",
        "  co-occurrence, and object-to-wall distances measured on full room "
        "floors. Here they come",
        "  from SUN RGB-D, with small samples for kitchens, bathrooms, and "
        "other room types (see the",
        "  omitted table).",
        "- 3D-FUTURE model metadata: real catalog dimensions, style labels, and material labels.",
        "  Here `style_tags` and `material` are project labels and dimensions are SUN RGB-D",
        "  measurements plus Objaverse mesh proportions.",
        "- 3D-FUTURE meshes for catalog thumbnails or 3D views. Only the 141 cleaned Objaverse",
        "  meshes exist.",
        "",
        "The optimizer does not need them. Numbers from the ATISS paper were not used.",
        "",
    ]
    # Join the lines.
    return "\n".join(out)


def run() -> str:
    """Write the report file and return its path."""
    # Target path.
    path = repo_root() / "docs" / "reports" / "data_quality_layout.md"
    # Folder exists from Phase 2a, but be safe.
    path.parent.mkdir(parents=True, exist_ok=True)
    # Write the text.
    path.write_text(build(), encoding="utf-8")
    # Give the path back.
    return str(path)
