"""Render docs/reports/data_quality_cv.md from the cleaning summaries in datasets/metadata/cleaning/."""

# Annotations on Python 3.11.
from __future__ import annotations

# Shared paths and JSON helpers.
from spacedesigner.data.common import cleaning_dir, read_json, repo_root

# Taxonomy lists written into the report.
from spacedesigner.data.taxonomy import FURNITURE_CLASSES, ROOM_TYPES


def table(mapping: dict, key_header: str, value_header: str = "count") -> list[str]:
    """Render a {key: value} mapping as a two-column Markdown table."""
    # Header rows.
    lines = [f"| {key_header} | {value_header} |", "| --- | ---: |"]
    # One row per key.
    for key, value in mapping.items():
        # Escape pipes so cells stay intact.
        lines.append(f"| {str(key).replace('|', '/')} | {value} |")
    # Blank line after the table.
    return lines + [""]


def wide_table(columns: list[str], rows: dict[str, dict]) -> list[str]:
    """Render {row: {column: value}} as a table with one column per key."""
    # Header.
    lines = [
        "| class | " + " | ".join(columns) + " |",
        "| --- | " + " | ".join("---:" for _ in columns) + " |",
    ]
    # Every row label that appears in any column.
    labels = sorted({label for col in rows.values() for label in col})
    # One row per label.
    for label in labels:
        # Counts per column, zero when absent.
        cells = " | ".join(str(rows[col].get(label, 0)) for col in columns)
        # Add the row.
        lines.append(f"| {label} | {cells} |")
    # Blank line after the table.
    return lines + [""]


def render() -> str:
    """Build the whole report as one Markdown string."""
    # Folder of summaries.
    folder = cleaning_dir()
    # Load each summary.
    nyu = read_json(folder / "nyu_summary.json")
    # SUN RGB-D summary.
    sun = read_json(folder / "sun_rgbd_summary.json")
    # Places summary.
    places = read_json(folder / "places_summary.json")
    # CubiCasa summary.
    cubi = read_json(folder / "cubicasa_summary.json")
    # Structured3D summary.
    s3d = read_json(folder / "structured3d_summary.json")
    # Output lines.
    out: list[str] = ["# Phase 2a data quality report (CV datasets)", ""]
    # Intro.
    out += [
        "Generated by `uv run python scripts/clean_report.py` from `datasets/metadata/cleaning/*.json`. "
        "Cleaned images, masks, and labels are under `datasets/processed/` and are gitignored.",
        "",
        "## Unified taxonomy",
        "",
        f"Furniture classes ({len(FURNITURE_CLASSES)}), in YOLO id order: "
        + ", ".join(f"`{i}` {name}" for i, name in enumerate(FURNITURE_CLASSES))
        + ".",
        "",
        f"Room types ({len(ROOM_TYPES)}): " + ", ".join(f"`{name}`" for name in ROOM_TYPES) + ".",
        "",
        "Every furniture synonym is a label that appears in the SUN RGB-D 2D boxes or the NYU `names` "
        "list. `tests/data/test_taxonomy.py` checks this against "
        "`datasets/metadata/cleaning/*_label_vocabulary.json`.",
        "",
        "### Places365 indoor categories chosen",
        "",
        f"Chosen from the {places['places_categories_total']} official strings in "
        "`categories_places365.txt` (not from the val archive, which holds images only):",
        "",
    ]
    # Category table.
    out += table(places["places_categories_chosen"], "Places365 category", "room type")
    # NYU section.
    out += [
        "## NYU Depth V2",
        "",
        f"- Frames: {nyu['frames']} exported {nyu['frames_exported']} (official split: {nyu['split_frames']}).",
        f"- Raw classes: {nyu['raw_classes']}; mapped to the taxonomy: {nyu['raw_classes_mapped_to_taxonomy']}; "
        f"left as `other` (label 0): {nyu['raw_classes_unmapped']}. Label map values: 255 unlabeled, "
        "0 other, k+1 furniture class k.",
        f"- Depth is raw Kinect depth in metres. Readings of 0, non-finite, or outside {nyu['depth_valid_range_m']} m "
        f"are set to 0.0 (no NaN). Mean invalid share {nyu['mean_invalid_depth_fraction']}; "
        f"{nyu['frames_with_over_half_invalid_depth']} frames have more than half of their depth invalid.",
        "- No validation split: the official `splits.mat` has only train and test.",
        "",
    ]
    # NYU pixel histogram.
    out += table(nyu["pixels_per_taxonomy_class"], "taxonomy class", "labeled pixels")
    # NYU scenes.
    out += table(nyu["room_type_histogram"], "room type (from NYU scene type)", "frames")
    out += [
        "NYU scene types not mapped to a room type: "
        + ", ".join(f"{k} ({v})" for k, v in nyu["scene_types_unmapped"].items())
        + ".",
        "",
    ]
    # SUN section.
    out += [
        "## SUN RGB-D",
        "",
        f"- Images in `SUNRGBDMeta2DBB_v2.mat`: {sun['images_in_meta']}; readable: {sun['images_readable']}; "
        f"with at least one kept box: {sun['images_with_labels']}.",
        f"- Boxes: {sun['boxes_raw']} raw, {sun['boxes_kept']} kept, {sun['boxes_clipped_to_edge']} of the kept boxes were clipped to the image edge. "
        "Coordinates are MATLAB 1-based `[x, y, w, h]` and are converted to 0-based YOLO.",
        f"- Split (grouped by SUN3D location, stratified by sensor and scene): {sun['split_images']}; with labels: {sun['split_labeled_images']}.",
        f"- Test images with depth and a 3D room layout copied for Phase 7b: {sun['test_images_with_depth_and_layout']}. "
        "The layout comes from `annotation3Dlayout/index.json` inside `SUNRGBD.zip`; no required layout file is missing, "
        "and `SUNRGBDMeta3DBB_v2.mat` was not needed.",
        f"- {sun['images_overlapping_nyu_depth_v2']} SUN RGB-D images are the NYU Depth V2 frames (`kv1/NYUdata`). "
        "They are flagged `overlaps_nyu_depth_v2` in the manifest. SUN and NYU splits are independent, so a frame can be "
        "train in one and test in the other. Phase 7a must not report NYU test metrics on a model trained with those SUN images without excluding them.",
        "",
        "### Boxes dropped, by reason",
        "",
    ]
    # Drop reasons.
    out += table(sun["boxes_dropped_by_reason"], "reason")
    out += [
        "`unmapped_class` covers the many SUN labels (cups, monitors, paper, and so on) that are not in the 26-class taxonomy.",
        "",
    ]
    # Split by sensor.
    out += table(sun["split_by_sensor"], "split | sensor", "images")
    # Class histogram.
    out += ["### Box class histogram by split", ""]
    out += wide_table(["train", "val", "test"], sun["class_histogram_by_split"])
    out += [
        "`rug` and `window` have very few SUN RGB-D boxes (25 and 37 in train). A detector fine-tuned on this label set will be weak on them.",
        "",
    ]
    # Room-type source.
    out += ["### SUN scene labels mapped to room types", ""]
    out += table(sun["room_type_histogram"], "room type", "images")
    out += [
        "Scenes not mapped (dropped from the room-type set): "
        + ", ".join(f"{k} ({v})" for k, v in sun["scene_unmapped_to_room_type"].items())
        + ".",
        "",
    ]
    # Places section.
    out += [
        "## Places365 indoor and the room-type dataset",
        "",
        f"- **The Places365 train archive is not on disk.** Only `val_256.tar` ({places['places_val_images_total']} images, 100 per class) is available, "
        "so this phase cannot build a Places train split. The Places images here are the val images; they are split 80/10/10 by this project, "
        "and results on them must not be quoted as the official Places365 validation score.",
        f"- Val images in the {len(places['places_categories_chosen'])} chosen classes: {places['places_val_images_in_chosen_classes']}; "
        f"outside them: {places['places_val_images_not_indoor_class']}. Corrupt or wrong-size images: {places['places_dropped_by_reason']}.",
        f"- Near-duplicates (dHash within {places['near_duplicate_bits']} of 64 bits): {sum(places['near_duplicates_dropped_by_room'].values())} dropped.",
        f"- Balance: at most {places['balance_cap_per_room']} images per room type. Places images are kept first; SUN RGB-D images fill the rest by seeded sample. "
        "SUN images keep their detection split so no image sits in two splits.",
        f"- Final: {places['final_images']} images ({places['final_by_source']}).",
        "",
    ]
    # Room-type table.
    out += table(places["final_by_room_type"], "room type", "images")
    # Split table.
    out += table(places["final_by_split"], "split", "images")
    # Cap drops.
    out += ["### Dropped by the balance cap", ""]
    out += table(
        {k: v for k, v in places["balance_cap_dropped_by_room"].items() if v},
        "room type",
        "images dropped",
    )
    out += [
        "Room types `closet`, `entrance_hall`, `utility_room`, `pantry`, and `home_theater` come only from Places val (100 images each, fewer after the split). "
        "`balcony` and `basement` are small.",
        "",
    ]
    # CubiCasa section.
    out += [
        "## CubiCasa5K",
        "",
        f"- License: {cubi['license']} (the blueprint's CC BY-NC 4.0 is superseded by the Zenodo record).",
        f"- Plans in the zip: {cubi['svg_plans_in_zip']}; kept: {cubi['plans_kept']}; dropped: {cubi['plans_dropped']} ({cubi['plans_dropped_by_reason']}).",
        f"- Official splits kept: {cubi['split_plans']}. Collections: {cubi['collection_plans']}.",
        f"- Floors: {cubi['floors_total']}; walls: {cubi['walls_total']}; doors: {cubi['doors_total']}; windows: {cubi['windows_total']}; room polygons: {cubi['rooms_total']}.",
        "- Doors and windows are nested inside their wall groups in the SVG and are read from there.",
        "- Output is polygons (JSON) plus a structure mask (0 background, 1 wall, 2 door, 3 window) and a room mask per floor. No parser is trained (Phase 12).",
        "",
        "### Polygons dropped, by reason",
        "",
    ]
    # Polygon drops.
    out += table(cubi["polygons_dropped_by_reason"], "reason")
    # Room classes.
    out += ["### Room class histogram", ""]
    out += table(cubi["room_class_histogram"], "CubiCasa space class", "polygons")
    # Structured3D section.
    out += [
        "## Structured3D (annotation and bbox zips only)",
        "",
        f"- Scenes: {s3d['scenes_exported']} of {s3d['scenes_in_annotation_zip']} (official split {s3d['split_scenes']}). "
        f"{s3d['scenes_without_bbox_3d']} scenes have no `bbox_3d.json`.",
        f"- Rooms exported with exact dimensions (mm to m): {s3d['rooms_exported']}. Dropped: {s3d['rooms_dropped_by_reason']}.",
        f"- Room footprint convex-hull area percentiles (m²): {s3d['hull_area_m2_percentiles']}.",
        "- `bbox_3d.json` holds oriented 3D boxes without class names; only counts are recorded.",
        "- **Perspective RGB and depth zips are not on disk.** No scene has an image, depth, and layout triple "
        f"(`scenes_complete_for_photo_or_depth_check` = {s3d['scenes_complete_for_photo_or_depth_check']}). "
        f"The bbox zip contains {s3d['perspective_instance_masks_in_bbox_zip']} perspective instance masks, which are label renders, not photos. "
        "Phase 7b cannot run Structured3D photo or depth checks until perspective parts are added.",
        "",
    ]
    # Room types.
    out += table(s3d["room_type_histogram"], "Structured3D room type", "rooms")
    # Not cleaned section.
    out += [
        "## Not cleaned because the bytes are not on disk",
        "",
        "- Places365 train archive (about 24 GB): no Places train split.",
        "- Structured3D `perspective_full_00` and `perspective_full_01`: no photo, depth, or image-plus-layout scenes.",
        "- 3D-FRONT and 3D-FUTURE, FurniScene: not in this phase (layout priors, INR catalog, and synthetic generator belong to Phase 2b).",
        "- NYU raw 428 GB capture, `SUNRGBDMeta3DBB_v2.mat`: not taken and not needed here.",
        "- Objaverse mesh cleanup and RAG chunking: Phase 2b.",
        "",
        "## Checks",
        "",
        "`uv run pytest tests/data` validates the exported data: no NaN, boxes inside image bounds, all classes inside the taxonomy, and no image in two splits. "
        "Those tests skip when `datasets/processed/` is absent.",
        "",
    ]
    # Join into a document.
    return "\n".join(out)


def run() -> str:
    """Write the report file and return its path."""
    # Target path.
    path = repo_root() / "docs" / "reports" / "data_quality_cv.md"
    # Folder.
    path.parent.mkdir(parents=True, exist_ok=True)
    # Write the text.
    path.write_text(render(), encoding="utf-8")
    # Report where it went.
    return str(path)
